<?php

namespace ContainerTG6Cxux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OacbV0iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.oacbV0i' shared service.
     *
     * @return \http\Env\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AuthorController::create()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".');
    }
}
