<?php

namespace ContainerTG6Cxux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2i30GNWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2i30GNW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2i30GNW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthorController::allAuthors' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\AuthorController::create' => ['privates', '.service_locator.s.ILJ8n', 'get_ServiceLocator_S_ILJ8nService', true],
            'App\\Controller\\AuthorController::exactAuthor' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\BookController::allBooks' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController::exactBook' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AuthorController:allAuthors' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\AuthorController:create' => ['privates', '.service_locator.s.ILJ8n', 'get_ServiceLocator_S_ILJ8nService', true],
            'App\\Controller\\AuthorController:exactAuthor' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\BookController:allBooks' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController:exactBook' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AuthorController::allAuthors' => '?',
            'App\\Controller\\AuthorController::create' => '?',
            'App\\Controller\\AuthorController::exactAuthor' => '?',
            'App\\Controller\\BookController::allBooks' => '?',
            'App\\Controller\\BookController::exactBook' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthorController:allAuthors' => '?',
            'App\\Controller\\AuthorController:create' => '?',
            'App\\Controller\\AuthorController:exactAuthor' => '?',
            'App\\Controller\\BookController:allBooks' => '?',
            'App\\Controller\\BookController:exactBook' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
