<?php

namespace ContainerTG6Cxux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S_ILJ8nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s.ILJ8n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s.ILJ8n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.oacbV0i', NULL, 'Cannot determine controller argument for "App\\Controller\\AuthorController::create()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
