<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzsiaab\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzsiaab/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPzsiaab.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPzsiaab\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPzsiaab\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pzsiaab',
    'container.build_id' => 'c978fd29',
    'container.build_time' => 1684245759,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzsiaab');
